name = "Cartel [Advanced]"
author = "gavinhsmith"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51fd99d9d4ceb74d90732c43fde49a8df05ecb7c98de2d3b7816f2f346f15319"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.20"]
