name = "Cartel [Advanced]"
author = "gavinhsmith"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d900fa00086e65e440c58d051fd650648656025b21ebd0890018e3f7ae51f69e"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.20"]
