name = "Cartel"
author = "gavinhsmith"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b4a983a094aeb358058d7e88bd30b6980967facbc3309370c5ab489711ff023"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
