name = "Cartel"
author = "gavinhsmith"
version = "1.1.0-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba08c09befc61af660861996d09c3291dc0f8fe7505a930bda3850a6ee8bc00"

[versions]
fabric = "0.15.11"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.4", "1.20.5", "1.20.6"]
