name = "Cartel"
author = "gavinhsmith"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd9e118e0784463a1c0970d5f614cc7a3bb426954847f3d997fd225516b485d7"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1", "1.21"]
