name = "Cartel [Enhanced]"
author = "gavinhsmith"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae3b6f36205b3837643e12215b3f3cebace641550a4882d0bd3a988235b7e9a7"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.1", "1.21"]
