name = "Cartel [Lite]"
author = "gavinhsmith"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c944ba47f006dae5352fad6c625e26d842382e0a376554f5c54ba808727cd6f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
