name = "Cartel [Lite]"
author = "gavinhsmith"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "463f9516bbf2fb705669268dd21d66df85f1335abfb25e5f243e90405f29bc6f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
