name = "Cartel [Base]"
author = "gavinhsmith"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed236761315253d5048762c106790743da8e97dec3400da692de0d4f5aeddb09"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
